// <auto-generated />
namespace Landlord.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class tenantupdate5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tenantupdate5));
        
        string IMigrationMetadata.Id
        {
            get { return "201808232024077_tenantupdate5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
